project:
  type: website

website:
  title: "QTM350 QUIZ 2"
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: country.qmd
        text: Country Analysis
      - href: life-gdp.qmd
      - href: life-population.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

output-dir: docs

